Repository MIERUNE/plateau-gis-converter, pull requests merged in 2024-03, with the labels that each got.

#404 デバッグビルドで依存ライブラリに最適化をかける
  Cargo.toml
Labels: CI & Bulid

#402 GUI: Tauriによるログ出力
  app/package-lock.json
  app/package.json
  app/src-tauri/Cargo.toml
  app/src-tauri/src/main.rs
  app/src/routes/+page.svelte
Labels: GUI

#393 3dtiles: structural metadata のエンコーダ
  nusamai/src/sink/cesiumtiles/gltf.rs
  nusamai/src/sink/cesiumtiles/material.rs
  nusamai/src/sink/cesiumtiles/metadata/mod.rs
  nusamai/src/sink/cesiumtiles/mod.rs
  nusamai/src/sink/cesiumtiles/utils.rs
  nusamai/src/sink/mod.rs
  nusamai/src/transformer/builder.rs
  nusamai/src/transformer/transform/appearance.rs
  nusamai/src/transformer/transform/jsonify.rs
Labels: 3D Tiles

#439 Feedback機構を少し改善
  nusamai-citygml/src/object.rs
  nusamai/src/main.rs
  nusamai/src/pipeline/feedback.rs
  nusamai/src/pipeline/runner.rs
  nusamai/src/sink/cesiumtiles/mod.rs
  nusamai/src/sink/cesiumtiles/tiling/scheme.rs
  nusamai/src/sink/czml/mod.rs
  nusamai/src/sink/geojson/mod.rs
  nusamai/src/sink/kml/mod.rs
  nusamai/src/sink/mvt/mod.rs
  nusamai/src/sink/noop/mod.rs
  nusamai/src/sink/ply/mod.rs
  nusamai/src/sink/serde/mod.rs
  nusamai/src/sink/shapefile/mod.rs
  nusamai/tests/pipeline.rs
Labels: Controller

#447 gltf: JPEG は元データをそのまま埋め込む
  nusamai-gltf/nusamai-gltf-json/src/models/image.rs
  nusamai/Cargo.toml
  nusamai/src/sink/cesiumtiles/gltf.rs
  nusamai/src/sink/cesiumtiles/material.rs
  nusamai/src/sink/cesiumtiles/mod.rs
  nusamai/src/sink/gltf/gltf_writer.rs
  nusamai/src/sink/gltf/material.rs
  nusamai/src/sink/gltf/mod.rs
Labels: 3D Tiles, glTF

#449 LTO: lto = fat に戻す
  Cargo.toml
  nusamai-citygml/macros/src/derive.rs
  nusamai-citygml/macros/src/type_attrs.rs
  nusamai-citygml/src/appearance.rs
  nusamai-citygml/src/attribute.rs
  nusamai-citygml/src/parser.rs
  nusamai-citygml/src/values.rs
Labels: CI & Bulid

#466 chore: サンプルファイルの Cesium を v1.115 に更新
  demo/cesium/3dtiles.html
  demo/cesium/czml.html
  demo/cesium/gltf_ext_mesh_features.html
  demo/cesium/gltf_ext_structural_metadata.html
  docs/manual/use_gui.md
Labels: 3D Tiles

#461 GUI: キャンセル可能にする & 変換ログを表示する（いずれも初期的実装）
  app/package-lock.json
  app/package.json
  app/src-tauri/src/main.rs
  app/src-tauri/tauri.conf.json
  app/src/routes/+page.svelte
  app/src/routes/LoadingAnimation.svelte
  nusamai/src/pipeline/feedback.rs
  nusamai/src/pipeline/mod.rs
  nusamai/src/pipeline/runner.rs
  nusamai/src/sink/mvt/mod.rs
  nusamai/src/source/citygml.rs
Labels: GUI

#463 parser: gml:MultiGeometry をパースできるようにする
  nusamai-citygml/src/parser.rs
Labels: 3D Tiles

#469 hotfix: JsonifyTransformer
  nusamai/src/transformer/transform/jsonify.rs
Labels: 3D Tiles

#470 多くの変換ログを log crate → Feedback に移行する
  app/src/routes/LoadingAnimation.svelte
  nusamai/src/sink/cesiumtiles/gltf.rs
  nusamai/src/sink/cesiumtiles/material.rs
  nusamai/src/sink/cesiumtiles/mod.rs
  nusamai/src/sink/gltf/gltf_writer.rs
  nusamai/src/sink/gltf/material.rs
  nusamai/src/sink/gltf/mod.rs
  nusamai/src/sink/gpkg/mod.rs
  nusamai/src/sink/noop/mod.rs
  nusamai/src/sink/serde/mod.rs
  nusamai/src/transformer/mod.rs
  nusamai/src/transformer/runner.rs
  nusamai/src/transformer/transform/appearance.rs
  nusamai/src/transformer/transform/attrname.rs
  nusamai/src/transformer/transform/dots.rs
  nusamai/src/transformer/transform/flatten.rs
  nusamai/src/transformer/transform/geommerge.rs
  nusamai/src/transformer/transform/jsonify.rs
  nusamai/src/transformer/transform/lods.rs
  nusamai/src/transformer/transform/mod.rs
  nusamai/src/transformer/transform/projection.rs
Labels: GUI, Controller

#474 Fix SQLite's DSN handling (for Windows)
  nusamai-gpkg/src/handler.rs
  nusamai/src/sink/gpkg/mod.rs
Labels: gpkg

#472 feedback.ensure_canceled()? を随所に仕込む
  nusamai/src/sink/czml/mod.rs
  nusamai/src/sink/geojson/mod.rs
  nusamai/src/sink/gltf/mod.rs
  nusamai/src/sink/gpkg/mod.rs
  nusamai/src/sink/kml/mod.rs
  nusamai/src/sink/mvt/mod.rs
  nusamai/src/sink/ply/mod.rs
  nusamai/src/sink/serde/mod.rs
  nusamai/src/sink/shapefile/mod.rs
  nusamai/src/source/citygml.rs
Labels: Controller

#475 CIでのリリースビルドで lto="fat" にする
  .github/workflows/release.yaml
Labels: CI & Bulid

#476 CI: リリースビルド時のオプションでビルドプロファイルを切り替える
  .github/workflows/release.yaml
Labels: CI & Bulid

#479 CLI: 入力ファイルが1つも見つからないときはエラー終了する
  nusamai/src/main.rs
Labels: Controller

#481 MVTなど用に maxHeight と minHeight を付与する Transformer
  demo/mvt/index.html
  nusamai-projection/src/crs.rs
  nusamai/src/sink/mod.rs
  nusamai/src/sink/mvt/mod.rs
  nusamai/src/transformer/builder.rs
  nusamai/src/transformer/transform/attrname.rs
  nusamai/src/transformer/transform/geomstats.rs
  nusamai/src/transformer/transform/mod.rs
  nusamai/src/transformer/transform/projection.rs
Labels: mvt

#488 GUI: 出力形式が切り替えられたとき、必要に応じて出力先CRSをリセットする
  app/src/routes/SettingSelector.svelte
Labels: GUI

#492 Fix: glTF Sink で interior rings を正しく扱うようにする
  nusamai/src/sink/cesiumtiles/material.rs
  nusamai/src/sink/cesiumtiles/slice.rs
  nusamai/src/sink/gltf/material.rs
  nusamai/src/sink/gltf/mod.rs
Labels: bug, glTF

#493 gltf(propertyTables): idを2重に書き込んでいた箇所を修正
  nusamai/src/sink/cesiumtiles/metadata/mod.rs
  nusamai/src/sink/gltf/metadata/mod.rs
Labels: bug, 3D Tiles, glTF

#498 GUI: 3D Tiles 出力のCRS選択肢にJGD2011を追加する（ジオイド高を加算しない用途）
  app/src/lib/settings.ts
Labels: enhancement, 3D Tiles

#485 gltf: 頂点ごとでの Mutex lock の除去
  README.md
  app/src-tauri/Cargo.toml
  nusamai-citygml/src/object.rs
  nusamai-citygml/src/values.rs
  nusamai-geometry/Cargo.toml
  nusamai-gltf/Cargo.toml
  nusamai-gpkg/Cargo.toml
  nusamai-projection/Cargo.toml
  nusamai-projection/src/jprect.rs
  nusamai/Cargo.toml
  nusamai/src/sink/cesiumtiles/mod.rs
  nusamai/src/sink/gltf/mod.rs
  nusamai/src/source/citygml.rs
Labels: glTF

#499 gltf: BoundingVolumeの height の更新の誤りを修正
  nusamai/src/sink/gltf/mod.rs
Labels: glTF

#502 CI: Mac用リリースを Universal Binary (Apple Silicon & Intel) にする
  .github/workflows/release.yaml
Labels: CI & Bulid

#503 CI: ターゲット aarch64-apple-darwin を追加する
  .github/workflows/release.yaml
Labels: CI & Bulid

#509 geometry: 座標（頂点）として任意の型を使えるようにする
  nusamai-citygml/Cargo.toml
  nusamai-citygml/src/geometry.rs
  nusamai-czml/Cargo.toml
  nusamai-czml/src/conversion.rs
  nusamai-geojson/Cargo.toml
  nusamai-geojson/src/conversion.rs
  nusamai-geometry/Cargo.toml
  nusamai-geometry/src/compact/linestring.rs
  nusamai-geometry/src/compact/mod.rs
  nusamai-geometry/src/compact/multi_linestring.rs
  nusamai-geometry/src/compact/multi_point.rs
  nusamai-geometry/src/compact/multi_polygon.rs
  nusamai-geometry/src/compact/polygon.rs
  nusamai-gltf/Cargo.toml
  nusamai-gltf/examples/geometry_to_gltf.rs
  nusamai-gltf/nusamai-gltf-json/Cargo.toml
  nusamai-gpkg/Cargo.toml
  nusamai-gpkg/src/geometry.rs
  nusamai-kml/src/conversion.rs
  nusamai-mvt/Cargo.toml
  nusamai-plateau/Cargo.toml
  nusamai-plateau/src/appearance.rs
  nusamai-shapefile/Cargo.toml
  nusamai-shapefile/src/conversion.rs
  nusamai/Cargo.toml
  nusamai/src/sink/cesiumtiles/mod.rs
  nusamai/src/sink/cesiumtiles/slice.rs
  nusamai/src/sink/cesiumtiles/utils.rs
  nusamai/src/sink/czml/mod.rs
  nusamai/src/sink/geojson/mod.rs
  nusamai/src/sink/gltf/mod.rs
  nusamai/src/sink/gltf/utils.rs
  nusamai/src/sink/gpkg/bbox.rs
  nusamai/src/sink/kml/mod.rs
  nusamai/src/sink/mvt/mod.rs
  nusamai/src/sink/mvt/slice.rs
  nusamai/src/sink/ply/mod.rs
  nusamai/src/sink/shapefile/mod.rs
Labels: Utilities

#510 ドキュメントの文言を修正
  README.md
  docs/manual/download_city_gml.md
Labels: documentation
